### ISSUE TITLE
Starting base container results in stat ./entrypoint.sh: no such file or directory".

### ISSUE THREAD

**Issue by nathanaherne** [reactioncommerce/base#1]
The full error when starting the base container is:

`docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"./entrypoint.sh\": stat ./entrypoint.sh: no such file or directory".`

Docker version = 17.03.0-ce-mac2 (15654)

This is after building the current master version from github. I have done some work to run base on Alpine Linux and I get the same issue when starting that container as well. I did this work to reduce the image size from 1.36GB for Debian to 1.1GB for Alpine (without trying to reduce size).

**Comment by jshimko** [comment]
What did you run to build the container?  (you need to use [`./build.sh`](v), not just `docker build ...`)

**Comment by jshimko** [comment]
Nobody else appears to be experiencing this issue, so I suspect it's from updates you've made.  I'm closing this for now, but if you believe there's an issue with this image, please feel free to reopen it.

**Comment by vineethEPM** [comment]
@jshimko : I'm getting the same error mentioned in this ticket.

docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"./entrypoint.sh\": stat ./entrypoint.sh: no such file or directory": unknown.

Process I followed:

1. docker-machine create
2. execute eval docker-machine env <droplet_name>
3. created a docker image build and tag my local repo
4. docker run command with parameters

I've my local repo conainting few custom imports with modifications
1. Have added reaction-swag-shop
2. Added payment with cash-on-delivery.

Please suggest if I'm missing anything.

**Comment by jshimko** [comment]
Can you please provide a repo and/or the exact commands you ran?  This unfortunately isn't enough detail for me to make any suggestions.

My first guess based on the wording of the original issue... 

> Starting base container...

and...

> The full error when starting the base container is:

First and most importantly, you don't _start_ the base container.  You use it to build Reaction by [adding it to the Reaction Dockerfile](https://github.com/reactioncommerce/reaction/blob/master/Dockerfile#L1) and running `docker build`.  Then you run _that_ image.  If you try to just run `reactioncommerce/base:latest`, the above error is the expected outcome because there's no built app inside of it yet.  That's pretty much the same as running `docker run ubuntu:latest`.  There's no app to run in that image either.  It's just a base image to build on top of.

**Comment by vineethEPM** [comment]
$ docker-machine create \
  --driver digitalocean \
  --digitalocean-access-token <token_name> \
  --digitalocean-size 2gb \
  easypeasy


$ eval "$(docker-machine env easypeasy)"

$ docker-machine ls

<img width="721" alt="screen shot 2018-02-08 at 8 43 20 pm" src="https://user-images.githubusercontent.com/35692006/35980450-ba754d6c-0d10-11e8-8970-532db51fc7a7.png">

$  docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t easypeasy .

$ docker images

<img width="653" alt="screen shot 2018-02-08 at 8 44 37 pm 1" src="https://user-images.githubusercontent.com/35692006/35980540-f08a968c-0d10-11e8-95f1-feae15e8a209.png">

$ docker push vineeth059/easypeasy:latest

$ docker run -d -p 80:3000 -e ROOT_URL="http://easypeasymart.in" -e MONGO_URL="mongodb://adminepm:adminepm@aws-ap-southeast-1-portal.2.dblayer.com:16522,aws-ap-southeast-1-portal.1.dblayer.com:16522/compose?authSource=admin&ssl=true" -e REACTION_EMAIL="admin@easypeasymart.in" -e REACTION_USER="admin@easypeasymart.in" -e REACTION_AUTH="EPMepm@2018" -e SKIP_FIXTURES=1 vineeth059/easypeasy:latest

This is where I get error mentioned above.

I've integrated reaction-swag-shop and payments-cod into **imports/plugins/custom** folder. And made some custom changes. Changes work perfectly fine in my local machine and no errors. However I do pass  SKIP_FIXTURES=1 when starting reaction.

Further more when I do 

$ docker ps

yields nothing

$ docker ps -a

gets me 

<img width="1172" alt="screen shot 2018-02-08 at 9 04 12 pm" src="https://user-images.githubusercontent.com/35692006/35981642-c26a4308-0d13-11e8-8fc2-162dcf983095.png">

**Comment by vineethEPM** [comment]
@jshimko : Do let me know if any additional details needed.

**Comment by jshimko** [comment]
Well... for one, there's no way that 154MB image has Reaction in it.  That's only 30MB bigger than the base image.

```sh
docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t reaction-test .
```
624MB for me...
```sh
docker images

REPOSITORY                  TAG                 IMAGE ID            CREATED                  SIZE
reaction-test               latest              64e880a54fc6        Less than a second ago   624MB
```
Do you have a repo I can look at?

**Comment by vineethEPM** [comment]
@jshimko Well you are right about the size. I've built images many times everytime it is 154MB and once i got it to 600+MB but as soon as i did docker login and run list of images, it was gone. I've shared the repo details privately. both in gitter and repo invite.

**Comment by jshimko** [comment]
@vineethEPM I had no problem building/running your repo, so I think there has to be a detail you're missing somewhere.  I recommend skipping all of that Docker Machine remote building stuff.  Just do everything on your local machine until you get it working.

Also, your repo has no custom plugins in it.  It's just Reaction 1.7.0 with no customizations.  I only mention it because part of your initial issue was that you said you weren't seeing your customizations.

**Comment by vineethEPM** [comment]
Found the issue, whenever I'm trying to create image for the local code base. It fetches from project_name/Dockerfile

In this file, it was always base file. When i changed it to reaction:latest instead of base:v3.0.0 image started building with 665MB. 

Need to figure out how to build image with my custom code in it.

@jshimko : The imports/plugins/custom was git ignored. Have pushed the changes now.
