### ISSUE TITLE
could we have a alpine-nodejs version?

### ISSUE THREAD

**Issue by medyagh** [reactioncommerce/base#2]
I was wondering if this project would work in alpine ? is there is a specific reason that debian was chosen over alpine?

**Comment by jshimko** [comment]
Hey @medyagh. It was really just because we (and a large percentage of developers) are more familiar with Debian/Ubuntu based OS's.  I'm certainly not against having a Reaction base image that uses Alpine, but back when I originally wrote this it wasn't worth taking the time to learn another OS and its package manager just to have a smaller image.  Correct me if I'm wrong, but that's essentially the only reason for using Alpine, right?  

Anyway, if you're familiar with Alpine and want to create a Reaction base with it, we'd be happy to accept a pull request.  I don't think we're interested in replacing the Debian build, but I think another optional Dockerfile that builds `reactioncommerce/reaction:lean` (or something) would be totally fine.

Let me know if you have any questions about how to build Reaction.

**Comment by medyagh** [comment]
Sweet, I will make a PR, which folder can I edit for the dockerfiles ?

The advantage of using alpine is it plays better kubernetes, I am making a sample reaction on minikube and kuberentes, and to be a good citizen you need to keep your images less than 600.

The current reaction image is a few gigabytes, my own apps images are less than 60 MB, (that way you can spin it up faster when it crashes) and use less resources. there is no need to ship the whole debian operating system if we never use it.  in kuberntes world, k8s will do the process management.

**Comment by jshimko** [comment]
Well, a little background on the current state of things... our image _used_ to be under 400mb, but we opted to include a few large things by default because of issues that were coming up regularly with our users.  

The first was MongoDB.  Forcing all users to have a database set up just to evaluate our default app image was a bit of a turn-off for a first time experience with the product.  We wanted to give be a single command to run to get a shop running.  Yeah, you could use a mongo image with docker-compose, but that required config files and was already starting to go over people's heads.  So we added Mongo to the image and fall back to using it when a user doesn't supply a `MONGO_URL`.  The obvious downside... 4-500mb of image size for a database that nobody should be using in production.  So yeah, that could be improved.

Then there was the Meteor download/install.  Meteor accounts for a huge part of the current image size.  We used to download it at the beginning of the build, build the app, and then remove Meteor altogether (a savings of over 1gb of image size).  But the problem people complained about then was build time.  The Meteor tools are a huge download and we have users all over the world with different amounts of available bandwidth.  Forcing people to download 1gb+ on every Docker build was not popular, so caching it became the lesser of two evils.

So, if you removed those two parts alone, you'd probably easily have it down below 400mb again. And that was on Debian.  Alpine would be even smaller.  But the build time would go back to being much longer for users with low bandwidth, so it's not going to be for everyone.  Also, because of the original issues mentioned above, I don't think we'll be able to make this lean build the default.  But there's nothing wrong with having a different image tag for it though.

As for what you need to add/modify, I think you should probably just create a new Dockerfile for this build and not edit the others that are there.  You'll probably also want to create a completely new folder full of build scripts too (unless you try to write the whole build inside the Dockerfile).  Maybe just create a folder called `alpine` in the root of the project and throw everything in there.

**Comment by jshimko** [comment]
Kind of related to this conversation, I just did a big refactor of this project to make images a lot smaller.  As of 2.0.0 of this project, Mongo and Meteor are no longer in the final image.  The result is Reaction builds that were previously over 2GB are now down to roughly 355MB.

So certainly feel free to contribute the Alpine image, but I just wanted to point out that you have a leaner base image option now.  It hasn't been officially released in Reaction yet, but it's merged into development and will be included in the next release.  If you'd like to use the new base image now, you can manually update your Dockerfile.

```dockerfile
FROM reactioncommerce/base:2.0.0
```
