### ISSUE TITLE
why docker-hub is 2 months behind?

### ISSUE THREAD

**Issue by medyagh** [reactioncommerce/base#3]
I was wondering why dockerhub is 2 month behind ?
https://hub.docker.com/r/reactioncommerce/reaction/tags/

**Comment by jshimko** [comment]
Your link is for the Reaction repo, not this base image.  The base image is here:

https://hub.docker.com/r/reactioncommerce/base/tags/

Reaction builds on top of that whenever we push a release.

`reactioncommerce/reaction:latest` is the latest [tagged release](https://github.com/reactioncommerce/reaction/tags) (eg. `v1.2.3`) on the master branch

`reactioncommerce/prequel:latest` is the latest commit on the development branch

The versions/releases of this project (`reactioncommerce/base`) are entirely separate from Reaction.

However, I am noticing that CircleCI didn't successfully push the `v1.2.0` release of Reaction for some reason, so that actually is a real issue.  That should've happened [20 days ago](https://github.com/reactioncommerce/reaction/releases).  I just manually built/pushed it though, so [it's there now](https://hub.docker.com/r/reactioncommerce/reaction/tags/).

**Comment by nygava** [comment]
Thanks for the response, yeah I noticed same thing, thanks for doing it manually. is there a reason to put CircleCi as middle man ? can we have docker hub just pick it up from the repo and do automated build ?

**Comment by medyagh** [comment]
Thanks for the response, yeah I noticed same thing. I saw base was built but the reactioncommerce/reaction was not built, when I tried to build myself manually, it had a non zero error on the clean up script.

thanks for doing it manually. is there a reason to put CircleCi as middle man ? can we have docker hub just pick it up from the repo and do automated build ?

**Comment by jshimko** [comment]
We use CircleCI for a variety of reasons, but it's largely because it's way more flexible and it's what we use/prefer on all of our projects.  Also, we're definitely not fans of just about any service Docker has ever put out, so I can't see us wanting to ditch CircleCI for them any time soon.  The UI and user experience of almost every Docker product (Docker Hub, Docker Cloud, etc.) can be really awful sometimes.  Docker is definitely an amazing tool and I use it all day every day, but in my opinion, they are simply not great at being a product company yet (at least not for anything that has a UI and runs in the browser).

Aside from that, I don't really consider Docker Hub automated builds to be in the same class as a more complete CI/CD product like CircleCI. The flexibility and integrations in Circle are just miles ahead of anything Docker Hub has going.  All Docker Hub builds do is run a build based on a single Dockerfile and put the image in your repo.  CircleCI allows you to do literally anything you can write a script for (tests, custom builds from different Dockerfiles, deployments, etc.).  I know you can do multiple builds on Docker Hub, but the only available configuration is to pick the branch, Dockerfile, and image tag.  It's way more flexible when you can run bash scripts or run your builds inside any Docker image you want.  That kind of stuff opens the door for an extensive list of use cases that just aren't possible with Docker Hub.
